/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class name_kevinross_tool_debuggable_DebuggableToolNative */

#ifndef _Included_name_kevinross_tool_debuggable_DebuggableToolNative
#define _Included_name_kevinross_tool_debuggable_DebuggableToolNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     name_kevinross_tool_debuggable_DebuggableToolNative
 * Method:    getGRegistryState
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_name_kevinross_tool_debuggable_DebuggableToolNative_getGRegistryState
  (JNIEnv *, jclass);

/*
 * Class:     name_kevinross_tool_debuggable_DebuggableToolNative
 * Method:    UpdateGObjectState
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_name_kevinross_tool_debuggable_DebuggableToolNative_UpdateGObjectState
  (JNIEnv *, jclass);

/*
 * Class:     name_kevinross_tool_debuggable_DebuggableToolNative
 * Method:    StartJdwp
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_name_kevinross_tool_debuggable_DebuggableToolNative_StartJdwp
  (JNIEnv *, jclass);

/*
 * Class:     name_kevinross_tool_debuggable_DebuggableToolNative
 * Method:    StopJdwp
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_name_kevinross_tool_debuggable_DebuggableToolNative_StopJdwp
  (JNIEnv *, jclass);

/*
 * Class:     name_kevinross_tool_debuggable_DebuggableToolNative
 * Method:    SetJdwpAllowed
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_name_kevinross_tool_debuggable_DebuggableToolNative_SetJdwpAllowed
  (JNIEnv *, jclass, jboolean);

/*
 * Class:     name_kevinross_tool_debuggable_DebuggableToolNative
 * Method:    ConfigureJdwp
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_name_kevinross_tool_debuggable_DebuggableToolNative_ConfigureJdwp
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
